spring:
  application:
    name: EasyImport
  mail:
    host: smtp.gmail.com
    port: 587
    username: easyimport.bg@gmail.com
    password: ebovdypfekrwlmgd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"  # Това игнорира SSL проверката (временно за тест)
    protocol: smtp

#  FOR DEPLOY
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyimportdb
    username: springuser
    password: 2605

# FOR LOCALHOST TEST
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/easy_import?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password: '2605'


  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never